// Generated by Vanilla Sample17_PoissonDiskGenerator!
// Samples are also optimized to minimize overlap during rotation and sorted from
// center to outer ones; .z is length(.xy)

#define VA_POISSON_DISK_SAMPLE_COUNT  (8)

static const float3 g_poissonDisk[VA_POISSON_DISK_SAMPLE_COUNT] = 
{ 
    +0.02419484, -0.15898436, +0.16081485,
    -0.25048900, +0.29649448, +0.38814136,
    +0.50659454, +0.11002195, +0.51840413,
    -0.60288119, -0.11781454, +0.61428493,
    +0.56148404, -0.44295132, +0.71517146,
    -0.20797935, -0.76271725, +0.79056495,
    +0.29824960, +0.79052281, +0.84491372,
    -0.75250280, +0.62998903, +0.98140031
}; 

